### ISSUE TITLE
Getting connection error when starting fresh project

### ISSUE THREAD

**Issue by AbhinavRobinson** [ozzyonfire/shopify-app-next#2]
I have added the `.env.local` and replacing `%PORT%` with 3000 in package.json. Running project after this results in this error:

```bash
shopify-app-next/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: connect ECONNREFUSED 127.0.0.1:62837
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 62837
}
```

Any insights? :)

**Comment by wisniewski94** [comment]
Maybe related? https://github.com/Shopify/cli/issues/750

updating deps could help

**Comment by ozzyonfire** [comment]
Yep this is a bug in the cli, that is still hanging around. However, I don't actually get this error (as much) when running everything through next.

When running a custom express server and trying to load a Next frontend, I get it whenever the server does a hot-reload. 

I'll investigate the template... I should upgrade the cli dependencies to their latest version and see if that helps.

**Comment by AbhinavRobinson** [comment]
![Screenshot 2023-03-17 at 4 54 05 PM](https://user-images.githubusercontent.com/32090909/225891409-75469e3b-3f8d-49a6-9323-e1f4e410f2d9.jpg)

Doing cli update didn't change much other than the error formatting :/

**Comment by TheSecurityDev** [comment]
This error happens when something tries to connect to the server before it has started up. It seems to me a very simple fix would be to not crash the app, but handle the error and log it only.

**Comment by ozzyonfire** [comment]
I did have some luck with the newest update from shopfy/cli - I will try to get a demo working for tomorrow.

**Comment by ozzyonfire** [comment]
Just tested with the latest package versions and HMR is working when running the NextJS project. Even my other project which uses a custom Express server to launch the NextJS application works when the server detects a change and it restarts the project (using tsc --watch). 

Hopefully this helps your use case, let me know if it doesn't - I will try to help, but it also may be more helpful to see if anyone has info on the cli repo page. https://github.com/Shopify/cli/issues

**Comment by AbhinavRobinson** [comment]
I am able to start the project now with a fresh clone! Awesome, thanks :)
